config/routes.rb
Rails.application.routes.draw do
  root 'quests#index'
  # get 'quests/:id/make_solved',to:'quests#make_solved'
  get 'quests/index_t',to:'quests#index_t'
  get 'quests/index_f',to:'quests#index_f'
  # patch 'quests/:id/make_solved' => 'quests#make_solved'
  devise_for :users

  resources(:users,{only:[:show,:index,:edit,:update,:destroy]})

  resources(:quests,{only:[:new,:create,:show,:destroy,:edit,:update]}) do 
    member do
      get 'make_solved'
    end

    collection do
      get 'search'
    end

    resources(:quest_answers,{only:[:create,:destroy]})
  end 

  resources(:users,{only:[:index,:show,:edit,:update]})
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :user
  has_many :quest_answers, dependent: :destroy
end

app/models/quest_answer.rb
class QuestAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :quest
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quests, dependent: :destroy
  has_many :quest_answers, dependent: :destroy
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/quest_answers_controller.rb
class QuestAnswersController < ApplicationController

  def create
    quest_answer=QuestAnswer.new(quest_answer_params)
    @quest=Quest.find(params[:quest_id])
    quest_answer.quest_id=@quest.id
    quest_answer.user_id=current_user.id
    if quest_answer.save
      QuestAnswerMailer.with(quest:@quest,quest_answer:quest_answer).creation_email.deliver_now
      redirect_to(quest_path(@quest),{notice:"回答を送信しました"})
    else
      reder quest_path(@quest)
    end  
  end

  def destroy
    QuestAnswer.find_by(id:params[:id],quest_id:params[:quest_id]).destroy
    redirect_to quest_path(params[:quest_id])
  end

  private

  def quest_answer_params
    params.require(:quest_answer).permit(:answer)
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

  before_action(:authenticate_user!,only:[:new,:create])  #ログインしてる人だけ質問投稿ページに飛べる

   before_action :set_q, only: [:index, :search] #検索機能

  def new
    @quest=Quest.new
  end

  def create
    @quest=Quest.new(quest_params)
    @quest.user_id = current_user.id

     if @quest.save
      User.all.each do |user|
        QuestMailer.with(user: user, quest: @quest).creation_email.deliver_now
      end  
    #   QuestMailer.creation_email(@quest).deliver_now
        redirect_to(root_path,notice:"質問『#{@quest.title}』の投稿が完了しました")
     else
      render(:new)
     end  
  end

   def edit
    @quest=Quest.find(params[:id])
   end

   def update
    @quest=Quest.find(params[:id])
    @quest.is_solved=true
    @quest.update(quest_params)
    redirect_to root_path
   end

   def make_solved
     @quest = Quest.find(params[:id])
     @quest.update(is_solved: true)
     redirect_to root_path
   end

  def index
    @quests=Quest.all
  end

  def index_t
    @quests=Quest.where(is_solved:true)
  end

  def index_f
    @quests=Quest.where(is_solved:false)
  end

  def show
    @quest=Quest.find(params[:id])
    @quest_answer=QuestAnswer.new
  end

  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy
    redirect_to root_path
  end

  def search
    @results = @q.result
  end


  private

  def set_q
    @q = Quest.ransack(params[:q])
  end
  
  
  def quest_params
   params.require(:quest).permit(:title,:content,:is_solved)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
      @user=User.find(params[:id])
      @quests=@user.quests.all
  end

  def index
    @users=User.all
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quest_answes_helper.rb
module QuestAnswesHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Question</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"btn btn-primary" %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path,class:"btn btn-primary" %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path,class:"btn btn-primary" %>
      </li>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/quests/edit.html.erb
<h2>質問編集</h2>
<%= form_with model:@quest, local:true do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/quests/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
  <%= link_to "ユーザー一覧" ,users_path,class:"navbar-brand" %>
  <%= link_to "質問一覧" ,root_path,class:"navbar-brand" %>
  
  <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

          <% if user_signed_in? %>
          
            <% if current_user.image.attached? %> 
             <%= image_tag current_user.user.image,class:"rounded-circle",widt:"50", height:"50" %>
      　    <% else %>
             <%= image_tag "no_image.jpeg",class:"rounded-circle",widt:"50", height:"50" %>
      　    <% end %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "マイページ",user_path(current_user) %></li>
            <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <li><a href="#">Menu3</a></li>
            <li><a href="#">Menu4</a></li>
          </ul>
         <% end %> 
   </li>
</nav> 

  




  <%= link_to '質問する', new_quest_path,class:"btn btn-primary" %>


<div class="row">
 <div class="col"></div>
  <div class="col-8">

     
      <%= search_form_for@q, url: search_quests_path,class:"form-inline my-2 my-lg-0" do |f| %>
        <%= f.label :title_or_content_cont,"質問検索" %>
        <%= f.search_field :title_or_content_cont,class:"form-control mr-sm-2 ml-3",placeholder:"検索ワード" %>
        <%= f.submit '検索',class:"btn btn-outline-success  my-2 my-sm-0" %>
      <% end %>
      <div class="mt-5">
      <%= link_to '全て' ,'/' ,class:"col-2 btn btn-outline-info" %>
      <%= link_to '解決済' ,'/quests/index_t',class:"col-2 btn btn-outline-info" %>
      <%= link_to '未解決','/quests/index_f' ,class:"col-2 btn btn-outline-info"%>
      </div>

  </div>
  <div class="col"></div>
 </div>


<%= link_to '全て' ,'/' %>
<%= link_to '解決済' ,'/quests/index_t' %>
<%= link_to '未解決','/quests/index_f' %>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>ユーザーネーム</th>
      <th>タイトル</th>
      <th>内容</th>
      <th>状況</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  　<% @quests.each do |quest| %>
    <tr>
      <th>
      <% if quest.user.image.attached? %> 
       <%= image_tag quest.user.image,class:"rounded-circle",widt:"50", height:"50" %>
      <% else %>
       <%= image_tag "no_image.jpeg",class:"rounded-circle",widt:"50", height:"50" %>
      <% end %>
      </th>
      <th>
      <% if quest.user.name? %>
       <%= quest.user.name %>
      <% else %>
       名無しさん
      <% end %> 
      </th>
      <th><%= quest.title %></th>
      <th><%= quest.content %></th>
      <th><%= link_to "#{quest.quest_answers.count} 件の回答", quest_path(quest.id) %></th>
      <th>
        <% if quest.is_solved == false && quest.user == current_user %>    　　<%# is_solved==false かつ　その質問を投稿したユーザーだけが”解決済”にできる  %>
          <button type="button" class="btn btn-danger"><%= link_to '未解決', controller: 'quests', action: 'make_solved', id: quest %></button>
        <% elsif quest.is_solved == false %>
          <button type="button" class="btn btn-danger">未解決</button>
        <% else %> 
          <button type="button" class="btn btn-success">解決済</button>
        <% end %>
      </th>
      <th>
        <% if quest.user == current_user %>
        <p><%= link_to "質問編集", edit_quest_path(quest.id) %></p>
        <% end %>
      </th>
      <th><%= link_to "質問詳細", quest_path(quest.id) %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/quests/index_f.html.erb
<%= link_to '全て' ,'/' %>
<%= link_to '解決済' ,'/quests/index_t' %>
<%= link_to '未解決','/quests/index_f' %>

<% @quests.each do |quest| %>
<div>
  <p>タイトル：<%= quest.title %></p>
  <p>内容：<%= quest.content %></p>
  <p>
    <% if quest.is_solved == false && quest.user == current_user %>    　　<%# is_solved==false かつ　その質問を投稿したユーザーだけが”解決済”にできる  %>
    <%= link_to '未解決', controller: 'quests', action: 'make_solved', id: quest %>
   <% elsif quest.is_solved == false %>
    未解決
   <% end %>
  </p>
  <p>ユーザーネーム：<%= quest.user.name %></p>
  <% if quest.user == current_user %>
   <p><%= link_to "質問編集", edit_quest_path(quest.id) %></p>
  <% end %>
  <p><%= link_to "質問詳細", quest_path(quest.id) %></p>

</div>
<% end %>

app/views/quests/index_t.html.erb
<%= link_to '全て' ,'/' %>
<%= link_to '解決済' ,'/quests/index_t' %>
<%= link_to '未解決','/quests/index_f' %>

<% @quests.each do |quest| %>
<div>
  <p>タイトル：<%= quest.title %></p>
  <p>内容：<%= quest.content %></p>
  <p>
   
    解決済 
   
  </p>
  <p>ユーザーネーム：<%= quest.user.name %></p>
  <% if quest.user == current_user %>
   <p><%= link_to "質問編集", edit_quest_path(quest.id) %></p>
  <% end %>
  <p><%= link_to "質問詳細", quest_path(quest.id) %></p>

</div>
<% end %>

app/views/quests/new.html.erb
   
   <h1>質問投稿フォーム</h1>
<%= form_with model: @quest,local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>内容</h4>
  <%= f.text_area :content %>
  <%= f.submit '投稿' %>
<% end %>

app/views/quests/search.html.erb
<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |quest| %>
      <tr>
        <td><%= quest.title %></td>
        <td><%= quest.content %></td>
        <td>
            <% if quest.is_solved == false && quest.user == current_user %>    　　<%# is_solved==false かつ　その質問を投稿したユーザーだけが”解決済”にできる  %>
              <%= link_to '未解決', controller: 'quests', action: 'make_solved', id: quest %>
            <% elsif quest.is_solved == false %>
              未解決
            <% else %> 
              解決済 
            <% end %>
        </td>
        <td><%= link_to '詳細', quest_path(quest) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '戻る', root_path %>

app/views/quests/show.html.erb
<% if @quest.user == current_user %>
    <%= link_to "削除", quest_path(@quest), method: :delete,data:{confirm: "本当に削除しますか？"} %>
<% end %>

  <p>タイトル：<%= @quest.title %></p>
  <p>内容：<%= @quest.content %></p>
  <p>ユーザーネーム：<%= @quest.user.name %></p>
  <p>投稿日時：<%= @quest.created_at.strftime('%Y/%m/%d') %></p>

  <div>
<p>回答件数：<%= @quest.quest_answers.count %></p>
<% @quest.quest_answers.each do |quest_answer| %>
  <%= quest_answer.user.name %>
  <%= quest_answer.created_at.strftime('%Y/%m/%d') %><%= quest_answer.answer %>

  <% if quest_answer.user == current_user %>
  <div>
    <%= link_to "削除", quest_quest_answer_path(quest_answer.quest, quest_answer), method: :delete %>
  </div>
  <% end %>
<% end %>
</div>
<div>
<%= form_with(model:[@quest, @quest_answer], local: true) do |f| %>
  <%= f.text_area :answer, rows:'5',placeholder: "回答をここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>ユーザー登録</h1>
<%= form_with model: @user,local:true do |f| %>
  <%= f.label :name,"ニックネーム" %>
  <%= f.text_field :name %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit '登録' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>

  <p>ニックネーム：<%= user.name %></p>

   <p><%= link_to "詳細", user_path(user.id) %></p>
<% end %>

app/views/users/show.html.erb
<% if @user == current_user %>
    <%= link_to "削除", user_path(@user), method: :delete,data:{confirm: "本当に削除しますか？"} %>
<% end %>
<% if @user == current_user %>
    <%= link_to "編集", edit_user_path(@user), method: :get %>
<% end %>

  <p>ニックネーム：<%= @user.name %></p>
  <%= image_tag @user.image if @user.image.attached? %>


<% if @user.name? %>
  <h1><%= @user.name %>さんの過去の質問一覧</h1>
<% else %>
  <h1>名無しさんの過去の質問一覧</h1>
<% end %>


<% @quests.each do |quest| %>
<div>
  <p>タイトル：<%= quest.title %></p>
  <p>内容：<%= quest.content %></p>
  <p>
   <% if quest.is_solved == false && quest.user == current_user %>    　　<%# is_solved==false かつ　その質問を投稿したユーザーだけが”解決済”にできる  %>
    <%= link_to '未解決', controller: 'quests', action: 'make_solved', id: quest %>
   <% elsif quest.is_solved == false %>
    未解決
   <% else %> 
    解決済 
   <% end %>
  </p>
  <% if quest.user == current_user %>
   <p><%= link_to "質問編集", edit_quest_path(quest.id) %></p>
  <% end %>
  <p><%= link_to "質問詳細", quest_path(quest.id) %></p>
</div>
<% end %>  